apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: testcases-claim
spec:
    accessModes:
      - ReadWriteMany
    resources:
        requests:
            storage: 5Gi
    selector:
        matchLabels:
            name: testcases